name: 'Generate Arch Repo database and upload'
inputs:
  RCLONE_S3_ACCESS_KEY_ID:
    required: true
  RCLONE_S3_SECRET_KEY:
    required: true
  RCLONE_S3_ENDPOINT:
    required: true
  dest_path:
    required: true
  repo_name:
    required: true
  gpg-privatekey:
    description: 'Your GPG private key, used to sign repo.'
  local_path:
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
  env:
    RCLONE_S3_ACCESS_KEY_ID: ${{ inputs.RCLONE_S3_ACCESS_KEY_ID }}
    RCLONE_S3_SECRET_KEY: ${{ inputs.RCLONE_S3_SECRET_KEY }}
    RCLONE_S3_ENDPOINT: ${{ inputs.RCLONE_S3_ENDPOINT }}
    dest_path: ${{ inputs.dest_path }}
    repo_name: ${{ inputs.repo_name }}
    gpg_key: ${{ inputs.gpg-privatekey }}
    local_path: ${{ inputs.local_path }}
