name: BUILD

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'package name on aur'
        required: true

jobs:
  buildAUR:  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{inputs.name}}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{inputs.name}}
        if-no-files-found: error