name: BUILD-test-R2

on:
  workflow_dispatch:

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [
          firefox-nightly-i18n-ach
        ]
      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPkgs: ${{ matrix.preinstall-pkgs }}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error
        
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}          
  uploadToR2:      
    runs-on: ubuntu-latest
    if: always()
    needs: [buildAUR]

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        id: download

      - name: Display structure of downloaded files
        run: ls -R ${{ steps.download.outputs.download-path }}
      
      - uses: ./create-db-and-upload-action-cloudflare-r2
        with:
          RCLONE_S3_ACCESS_KEY_ID: ${{ secrets.RCLONE_S3_ACCESS_KEY_ID }}
          RCLONE_S3_ENDPOINT: ${{ secrets.RCLONE_S3_ENDPOINT }}
          RCLONE_S3_SECRET_KEY: ${{secrets.RCLONE_S3_SECRET_KEY_ID}}
          dest_path: /repo/archlinux/repo
          repo_name: archlinux-sving1024
          gpg-privatekey: ${{ secrets.gpg_private_key }}
          local_path: ${{ steps.download.outputs.download-path }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./upload_packages/*.sig,./upload_packages/*.files,./upload_packages/*.db,./upload_packages/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
