name: build no aur

on:
  workflow_dispatch:

jobs:
  buildAUR:
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Makepkg Build and Check (Unmaintained)
      uses: edlanglois/pkgbuild-action@v1.1.9
      with: 
        pkgdir: ./pandoc-cli
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error